/**
 * Regenerates src/lib/beadcolors.gen.ts from https://github.com/maxcleme/beadcolors (MIT).
 * Usage: bun scripts/import-beadcolors.ts
 */
const REPO = "https://raw.githubusercontent.com/maxcleme/beadcolors/master";
const SOURCES = ["mard", "perler"] as const;

type Row = [code: string, name: string, hex: string];

function naturalCompare(a: string, b: string): number {
  return a.localeCompare(b, "en", { numeric: true });
}

async function fetchText(path: string): Promise<string> {
  const res = await fetch(`${REPO}/${path}`);
  if (!res.ok) throw new Error(`GET ${path}: ${res.status}`);
  return res.text();
}

function parse(csv: string): Row[] {
  return csv
    .split(/\r?\n/)
    .filter((line) => line.trim())
    .map((line) => {
      const [code, name, r, g, b] = line.split(",").map((s) => s.trim());
      if (!code || !name || r === undefined || g === undefined || b === undefined) throw new Error(`Bad row: ${line}`);
      const hex = "#" + [r, g, b].map((v) => Number(v).toString(16).padStart(2, "0")).join("").toUpperCase();
      // Some charts repeat the code as the name; drop it so the UI doesn't show "A1 A1".
      return [code, name === code ? "" : name, hex] as Row;
    })
    .sort((a, b) => naturalCompare(a[0], b[0]));
}

const license = (await fetchText("LICENSE")).trim();
const tables: string[] = [];
for (const source of SOURCES) {
  const rows = parse(await fetchText(`raw/${source}.csv`));
  tables.push(`export const ${source}: Row[] = ${JSON.stringify(rows, null, 0).replace(/\],\[/g, "],\n  [").replace(/^\[\[/, "[\n  [").replace(/\]\]$/, "],\n]")};`);
  console.log(`${source}: ${rows.length} colours`);
}

const out = `// GENERATED by scripts/import-beadcolors.ts — do not edit by hand.
// Colour data from https://github.com/maxcleme/beadcolors
/*
${license}
*/

export type Row = [code: string, name: string, hex: string];

${tables.join("\n\n")}
`;

await Bun.write(new URL("../src/lib/beadcolors.gen.ts", import.meta.url), out);
console.log("Wrote src/lib/beadcolors.gen.ts");
